---
openapi: 3.0.3
info:
  title: API V1
  version: v1

servers:
  - url: https://med-system-backend.onrender.com
  - url: http://localhost:3000

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SignInPayload:
      type: object
      properties:
        token:
          type: string
    SignInRequestBody:
      type: object
      properties:
        email:
          type: string
          example: admin@email.com
        password:
          type: string
          example: password
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
    Procedure:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
      required:
        - id
        - name
        - code
    EventProcedure:
      type: object
      properties:
        id:
          type: integer
        procedure:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        patient:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        hospital:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        health_insurance:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        patient_service_number:
          type: string
        date:
          type: string
          format: date
        room_type:
          type: string
        amount:
          type: string
        urgency:
          type: boolean
        payd_at:
          type: string
          format: date
      required:
        - procedure
        - patient
        - hospital
        - health_insurance
        - patient_service_number
        - date
        - room_type
        - amount
        - urgency
        - payd_at

    CreateEventProcedureRequest:
      type: object
      properties:
        procedure_id:
          type: integer
        patient_id:
          type: integer
        hospital_id:
          type: integer
        health_insurance_id:
          type: integer
        patient_service_number:
          type: string
        date:
          type: string
          format: date
        urgency:
          type: boolean
        room_type:
          type: string
      required:
        - procedure_id
        - patient_id
        - hospital_id
        - health_insurance_id
        - patient_service_number
        - date
        - urgency
        - room_type

    UnprocessableEntityResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string

paths:
  /users/tokens/sign_in:
    post:
      summary: Sign in
      tags:
        - Sign in
      responses:
        "200":
          description: JWT Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInPayload"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequestBody"

  /api/v1/users:
    get:
      summary: List users
      operationId: listUsers
      security:
        - BearerAuth: []
      tags:
        - Users
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination (default is 1)
        - in: query
          name: per_page
          schema:
            type: integer
          description: Number of items per page (default is 25)
      responses:
        "200":
          description: A list of users for the authenticated user (admin only)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized

  /api/v1/procedures:
    get:
      summary: List procedures
      operationId: listProcedures
      security:
        - BearerAuth: []
      tags:
        - Procedures
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination (default is 1)
        - in: query
          name: per_page
          schema:
            type: integer
          description: Number of items per page (default is 25)
      responses:
        "200":
          description: A list of procedures for the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Procedure"
        "401":
          description: Unauthorized

  /api/v1/event_procedures:
    get:
      summary: List event_procedures
      operationId: listEventProcedures
      security:
        - BearerAuth: []
      tags:
        - EventProcedures
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination (default is 1)
        - in: query
          name: per_page
          schema:
            type: integer
          description: Number of items per page (default is 25)
      responses:
        "200":
          description: A list of event_procedures for the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventProcedure"
        "401":
          description: Unauthorized
    post:
      summary: Create a new EventProcedure
      operationId: createEventProcedure
      tags:
        - EventProcedures
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventProcedureRequest"
      responses:
        "201":
          description: Event Procedure created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventProcedure"
        "401":
          description: Unauthorized
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
